 export const CREATE_DATA_REQUEST="CREATE_DATA_REQUEST" 
 export const CREATE_DATA_SUCCESS="CREATE_DATA_SUCCESS"
 export const CREATE_DATA_FAILURE="CREATE_DATA_FAILURE"

 // ADD DATA

 export const ADD_DATA_REQUEST="ADD_DATA_REQUEST" 
 export const ADD_DATA_SUCCESS="ADD_DATA_SUCCESS"
 export const ADD_DATA_FAILURE="ADD_DATA_FAILURE"

 //EDIT DATA

 export const EDIT_DATA_REQUEST="EDIT_DATA_REQUEST" 
 export const EDIT_DATA_SUCCESS="EDIT_DATA_SUCCESS"
 export const EDIT_DATA_FAILURE="EDIT_DATA_FAILURE"

 //DELETE

 export const DELETE_DATA_REQUEST="DELETE_DATA_REQUEST" 
 export const DELETE_DATA_SUCCESS="DELETE_DATA_SUCCESS"
 export const DELETE_DATA_FAILURE="DELETE_DATA_FAILURE"
 //

 